export class mockProducts {
  static searchProducts(input: Array<any>) {
    cy.intercept(
      {
        method: 'POST',
        url: '/babou/api/ardor/products/search',
      },
      {
        body: {
          Results: input,
          ResultsTotal: 192,
          SuppliersTotal: 44,
          AccurateCount: true,
          MaxPage: 4,
          OrganicSize: 48,
          QueryId: 'de5c5cca37ff8622bf399c90769bb40e',
          IndexName: 'dev_product',
          Aggregations: {
            Theme: [
              { Name: 'Safety', Count: 55 },
              { Name: 'Food', Count: 53 },
              { Name: 'Trade Show', Count: 51 },
              { Name: 'Organizations', Count: 45 },
              { Name: 'Entertainment', Count: 40 },
              { Name: 'Sports', Count: 40 },
              { Name: 'Aviation', Count: 4 },
              { Name: 'Camping', Count: 4 },
              { Name: 'Celestial', Count: 4 },
              { Name: 'Football', Count: 4 },
              { Name: 'Patriotic', Count: 4 },
            ],
            LineName: [
              { Name: 'DgroupTrevelyan', Count: 37 },
              { Name: 'BagWorld', Count: 35 },
              { Name: '4ideagoods', Count: 22 },
              { Name: 'Screen Printing Plus', Count: 18 },
              { Name: 'Timbuk2', Count: 1 },
              { Name: 'U S Flash & Technologies LLC', Count: 1 },
              { Name: 'Zonnerre', Count: 1 },
            ],
            Size: [
              { Name: 'M', Count: 245 },
              { Name: '2XL', Count: 244 },
              { Name: 'L', Count: 244 },
              { Name: 'S', Count: 244 },
              { Name: '7/8 "', Count: 5 },
              { Name: '1 1/4 "', Count: 4 },
              { Name: '10 " x 14 "', Count: 4 },
              { Name: '11 " x 17 "', Count: 4 },
              { Name: '3.375" x 2.125"', Count: 4 },
              { Name: '4 " x 5 "', Count: 4 },
              { Name: '10 1/2 " x 12 " x 1 1/2 "', Count: 2 },
              { Name: '12.5 "', Count: 2 },
              { Name: '13 " x 16 " x 6 "', Count: 2 },
              { Name: '15 " x 12 " x 4.5 "', Count: 2 },
              { Name: '16 oz', Count: 2 },
              { Name: '18 " x 36 "', Count: 2 },
              { Name: '2 " x 3 1/2 "', Count: 2 },
              { Name: '2 3/4"', Count: 2 },
              { Name: '2 7/8 " x 4 3/4 "', Count: 2 },
              { Name: '2.0 "', Count: 2 },
              { Name: '2.5 "', Count: 2 },
              { Name: '24 mm', Count: 2 },
              { Name: '26 mm', Count: 2 },
              { Name: '3 "', Count: 2 },
            ],
            TradeName: [
              { Name: 'SmashWrap', Count: 10 },
              { Name: 'Smashbox', Count: 8 },
              { Name: 'HitWear', Count: 3 },
              { Name: 'Nova', Count: 3 },
              { Name: 'The Classic Line', Count: 3 },
              { Name: 'Liberty Bags', Count: 1 },
              { Name: 'Majestic', Count: 1 },
              { Name: 'Novelty Series', Count: 1 },
              { Name: 'Puma', Count: 1 },
              { Name: 'PurpleG-Wiz', Count: 1 },
              { Name: 'Swivel Series', Count: 1 },
              { Name: 'Tough John', Count: 1 },
              { Name: 'Wonder', Count: 1 },
            ],
            Color: [
              { Name: 'Black Shades', Count: 91 },
              { Name: 'Medium Black', Count: 87 },
              { Name: 'Assorted', Count: 14 },
              { Name: 'Assorted Shades', Count: 14 },
              { Name: 'Medium Yellow', Count: 12 },
              { Name: 'Brass Metal', Count: 1 },
              { Name: 'Bright White', Count: 1 },
            ],
            Shape: [
              { Name: 'Food & Drink Shapes', Count: 32 },
              { Name: 'Shield Shapes', Count: 2 },
              { Name: 'Sign Shapes', Count: 2 },
              { Name: 'Time Shapes', Count: 2 },
              { Name: 'Diamond Shapes', Count: 1 },
              { Name: 'Furniture Shapes', Count: 1 },
              { Name: 'Holiday Shapes', Count: 1 },
              { Name: 'Religious Shapes', Count: 1 },
              { Name: 'Ribbon Shapes', Count: 1 },
              { Name: 'State & Country Shapes', Count: 1 },
              { Name: 'Triangle Shapes', Count: 1 },
            ],
            CategoryGroup: [
              { Name: 'T-SHIRTS', Count: 244 },
              { Name: 'SIGNS & DISPLAYS', Count: 49 },
              { Name: 'DECALS', Count: 45 },
              { Name: 'JOURNALS & DIARIES', Count: 29 },
              { Name: 'MESSENGER BAGS', Count: 8 },
              { Name: 'DECORATORS', Count: 4 },
              { Name: 'EMBLEMS', Count: 3 },
            ],
            CategoryValue: [
              { Name: 'T-Shirts-Unisex', Count: 244 },
              { Name: 'Signs & Displays-General', Count: 47 },
              { Name: 'Decals-Vinyl', Count: 33 },
              { Name: 'Watches-Analog-Wrist', Count: 16 },
              { Name: 'Jackets-Leather', Count: 12 },
              { Name: 'Baseball Caps-Six Panel', Count: 11 },
              { Name: 'Decals-General', Count: 9 },
              { Name: 'Kits-Travel', Count: 3 },
              { Name: 'Labels-Weather Resistant', Count: 3 },
              { Name: 'Memo Pads-Self-Stick Note Pads', Count: 3 },
              { Name: 'Mobile Accessories-General', Count: 3 },
              { Name: 'Mugs & Steins-Ceramic', Count: 3 },
            ],
            Material: [
              { Name: 'Cotton', Count: 255 },
              { Name: 'Vinyl', Count: 33 },
              { Name: 'Leather', Count: 28 },
              { Name: 'Polyester', Count: 27 },
              { Name: 'Twill', Count: 4 },
              { Name: 'Ceramic', Count: 3 },
              { Name: '210 Denier Polyester', Count: 1 },
              { Name: '210D Polyester', Count: 1 },
              { Name: '600 Denier with Leatherette Trim', Count: 1 },
              { Name: 'Denim', Count: 1 },
              { Name: 'Leatherette-Cardboard', Count: 1 },
              { Name: 'Marble', Count: 1 },
              { Name: 'Matte Finish Stock', Count: 1 },
            ],
            Supplier: [
              { Name: 'Douglasbridge Intl Inc. (asi/50710)', Count: 249 },
              { Name: 'Dimaggio-Pinnacle (asi/78150)', Count: 65 },
              { Name: 'Hit Promotional Products (asi/61125)', Count: 61 },
              { Name: 'J Industries Inc (asi/63010)', Count: 47 },
              { Name: 'Bagworld (asi/37980)', Count: 38 },
              { Name: 'DGroup Trevelyan (asi/47977)', Count: 37 },
              { Name: '4ideagoods.com (asi/55217)', Count: 23 },
              {
                Name: 'Mak Group Of Companies/Tomahawk Garment (asi/68595)',
                Count: 18,
              },
              { Name: 'Screen Printing Plus Corp (asi/85945)', Count: 18 },
              { Name: 'Headwear Canada (asi/60281)', Count: 17 },
              { Name: 'Pacific Bridge Inc (asi/75644)', Count: 11 },
              { Name: 'A A Patch Works, Inc (asi/30003)', Count: 10 },
              { Name: 'Colonial/Redi Record Corp (asi/81110)', Count: 10 },
              { Name: 'Glow Promotions (asi/57713)', Count: 10 },
              { Name: 'AuthentiBrand Inc (asi/30118)', Count: 9 },
              { Name: 'Nissin Cap & Bag (asi/30107)', Count: 8 },
              { Name: 'Ad-A-Day Co Inc (asi/31040)', Count: 7 },
              { Name: "IMARK/American Nat'l Supply Inc (asi/35579)", Count: 7 },
              { Name: 'Graphic Electronics Inc (asi/57990)', Count: 1 },
              { Name: 'Kross Incorporated (asi/65700)', Count: 1 },
              { Name: 'Macro Industries Inc (asi/68399)', Count: 1 },
              { Name: "Manufacturers' Direct Sls Inc (asi/68630)", Count: 1 },
              { Name: 'Mr. Button Products Inc (asi/72671)', Count: 1 },
              { Name: 'Purple Giraffe (asi/80086)', Count: 1 },
              { Name: 'RHB Marketing (asi/80274)', Count: 1 },
              { Name: 'S & S Activewear (asi/84358)', Count: 1 },
              { Name: 'SIMBA (asi/87296)', Count: 1 },
              { Name: 'Timbuk2 (asi/91272)', Count: 1 },
              { Name: 'US Flash & Technologies LLC (asi/93131)', Count: 1 },
            ],
            ImprintMethod: [
              { Name: 'Silkscreen', Count: 409 },
              { Name: 'Unimprinted', Count: 185 },
              { Name: 'Printed', Count: 77 },
              { Name: 'Pad Printed', Count: 4 },
              { Name: 'Hot Foil Stamping', Count: 1 },
              { Name: 'Patch', Count: 1 },
              { Name: 'Photo Etch', Count: 1 },
              { Name: 'Sublimation', Count: 1 },
              { Name: 'Vibraprint™ Process', Count: 1 },
              { Name: 'Woven', Count: 1 },
            ],
          },
          Diagnostics: {
            QueryBuildTime: 2,
            EngineTimes: [27, 3],
            SearchTime: 65,
            ParseTime: 0,
            AdProviderTime: 0,
          },
          PfpDiagnostics: {
            QueryBuildTime: 8,
            EngineTimes: [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            SearchTime: 17,
            ParseTime: 0,
            PfpMode: 'MAPPED',
            AdProviderTime: 50,
          },
        },
      }
    ).as('searchProducts');
  }
}
