import { Company } from '@esp/models';
import { getRandomNumbers, randomStringGenerator } from '../../../utils';
export const generateCompany = (data?: {}): Company => ({
  CreditLimit: 0,
  ShippingAccounts: [],
  Links: [],
  IsCustomer: true,
  IsSupplier: false,
  IsDecorator: false,
  IsProspect: false,
  IsAsiMember: false,
  CanEditVisibility: true,
  IsTaxExempt: false,
  TaxCertificates: [],
  WebsiteContactCount: 0,
  ProofType: 'Blank',
  PrimaryBrandColor: '#6A7281',
  IsCompany: true,
  IsPerson: false,
  Id: getRandomNumbers(4, 1)[0],
  Name: randomStringGenerator(5),
  IsActive: true,
  CreateDate: '2021-12-08T16:46:26.087Z',
  UpdateDate: '2021-12-08T16:46:26.087Z',
  LastActivityDate: '2021-12-08T16:46:25.5118985Z',
  Version: 1764599,
  Tags: [],
  Addresses: [
    {
      Id: getRandomNumbers(4, 1)[0],
      Name: randomStringGenerator(5),
      City: '',
      State: '',
      PostalCode: '',
      CountryType: '',
      Phone: {
        Id: getRandomNumbers(4, 1)[0],
        Type: 'Other',
        PhoneCode: '1',
        Country: 'US',
        IsPrimary: false,
      },
      IsPrimary: true,
      Type: 'GNRL',
    },
  ],
  Phones: [],
  Emails: [],
  Websites: [],
  Owner: {
    Id: 0,
    Name: '(Unknown)',
  },
  Creator: {
    Id: 0,
    Name: '(Unknown)',
  },
  OwnerId: 5826,
  AccessLevel: 'Everyone',
  IsVisible: true,
  IsEditable: true,
  ...data,
});
