export const MOCK_PRODUCT = {
  Id: 1,
  ProductId: 5074897,
  IsVisible: true,
  ShowMinMaxRange: true,
  PriceRange: 'Price form $18.50 - $42.95',
  AdjustmentType: 'string',
  Adjustment: 0,
  RoundPricesToTwoDecimal: true,
  Sequence: 4,
  Supplier: {
    Id: 0,
    Name: 'string',
    IconMediaLink: {
      Id: 0,
      MediaId: 0,
      FileType: 'string',
      FileUrl: 'string',
      OriginalFileName: 'string',
      OnDiskFileName: 'string',
      DownloadFileName: 'string',
      DownloadFileUrl: 'string',
      IsVisible: true,
    },
    AsiSupplierId: 0,
  },
  Status: 'string',
  Like: 'string',
  Note: `Seriously the most comfortable tshirt we've found! Great fit, runs true-to-size.`,
  Name: 'Adult Softspun Semi-Fitted Tee',
  Description: `This "better than basic" tee provides the perfect fit alone or with a polo underneath. Wait, underneath? Tha's what it said.Weird. Who's wearing a polo under a t-shirt? Soft edge tags minimize itching while the 1x1 rib at collar, cuff and waistband provide comfort at its best.`,
  Summary: `This "better than basic" tee provides the perfect fit alone or with a polo underneath. Wait, underneath? Tha's what it said.Weird. Who's wearing a polo under a t-shirt? Soft edge tags minimize itching while the 1x1 rib at collar, cuff and waistband provide comfort at its best.`,
  Number: 'string',
  DefaultMedia: {
    IsVisible: true,
    Sequence: 0,
    Id: 0,
    Type: 'string',
    Url: 'string',
    IsPrimary: true,
    IsVirtualSampleReady: true,
    Attributes: [0],
    IsAvailable: true,
    IsCustom: true,
  },
  Media: [
    {
      IsVisible: true,
      Sequence: 0,
      Id: 5074897,
      Type: 'string',
      Url: 'media/7005708',
      IsPrimary: true,
      IsVirtualSampleReady: true,
      Attributes: [0],
      IsAvailable: true,
      IsCustom: true,
    },
  ],
  Attributes: [
    {
      Id: 0,
      Name: 'string',
      Description: 'string',
      Type: 'string',
      TypeGroup: 'string',
      Roles: [0],
      IsRequired: true,
      IsMultiSelect: true,
      Values: [
        {
          IsVisible: true,
          Sequence: 0,
          Id: 0,
          Value: 'string',
          ValueGroup: 'string',
          Description: 'string',
          SetId: 0,
          Type: 'string',
          Number: 'string',
          ImageUrl: 'string',
          Media: [
            {
              IsVisible: true,
              Sequence: 0,
              Id: 0,
              Type: 'string',
              Url: 'string',
              IsPrimary: true,
              IsVirtualSampleReady: true,
              Attributes: [0],
              IsAvailable: true,
              IsCustom: true,
            },
          ],
          Charges: [0],
          VendorCode: 'string',
          PriceGridId: 0,
          DisplaySequence: 0,
          SKU: ['string'],
          CodedValue: 'string',
          IsAvailable: true,
          IsSelected: true,
        },
      ],
    },
  ],
  PriceGrids: [
    {
      IsVisible: true,
      Sequence: 0,
      Id: 0,
      Description: 'Color: All Sizes: XS, S, M, L',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'string',
          DiscountPercent: 0,
          CurrencyCode: 'USD',
          PreferredPrice: 0,
          PreferredPriceText: 'string',
          IsUndefined: true,
          Quantity: {
            From: 50,
            To: 99,
          },
          ItemsPerUnit: 0,
          PricePerUnit: 22.5,
          CostPerUnit: 0,
          UnitQuantity: 0,
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'string',
          DiscountPercent: 0,
          CurrencyCode: 'USD',
          PreferredPrice: 0,
          PreferredPriceText: 'string',
          IsUndefined: true,
          Quantity: {
            From: 100,
            To: 249,
          },
          ItemsPerUnit: 0,
          PricePerUnit: 20.0,
          CostPerUnit: 0,
          UnitQuantity: 0,
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'string',
          DiscountPercent: 0,
          CurrencyCode: 'USD',
          PreferredPrice: 0,
          PreferredPriceText: 'string',
          IsUndefined: true,
          Quantity: {
            From: 250,
            To: 500,
          },
          ItemsPerUnit: 0,
          PricePerUnit: 18.5,
          CostPerUnit: 0,
          UnitQuantity: 0,
        },
      ],
      PriceIncludes: 'string',
      UsageLevel: 'string',
      Attributes: [0],
      IsAvailable: true,
    },
    {
      IsVisible: true,
      Sequence: 0,
      Id: 0,
      Description: 'Color: All Sizes: XS, S, M, L',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'string',
          DiscountPercent: 0,
          CurrencyCode: 'USD',
          PreferredPrice: 0,
          PreferredPriceText: 'string',
          IsUndefined: true,
          Quantity: {
            From: 50,
            To: 99,
          },
          ItemsPerUnit: 0,
          PricePerUnit: 22.5,
          CostPerUnit: 0,
          UnitQuantity: 0,
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'string',
          DiscountPercent: 0,
          CurrencyCode: 'USD',
          PreferredPrice: 0,
          PreferredPriceText: 'string',
          IsUndefined: true,
          Quantity: {
            From: 100,
            To: 249,
          },
          ItemsPerUnit: 0,
          PricePerUnit: 20.0,
          CostPerUnit: 0,
          UnitQuantity: 0,
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'string',
          DiscountPercent: 0,
          CurrencyCode: 'USD',
          PreferredPrice: 0,
          PreferredPriceText: 'string',
          IsUndefined: true,
          Quantity: {
            From: 250,
            To: 500,
          },
          ItemsPerUnit: 0,
          PricePerUnit: 18.5,
          CostPerUnit: 0,
          UnitQuantity: 0,
        },
      ],
      PriceIncludes: 'string',
      UsageLevel: 'string',
      Attributes: [0],
      IsAvailable: true,
    },
  ],
  Charges: [
    {
      IsVisible: true,
      Sequence: 0,
      Id: 0,
      Name: 'string',
      Description: 'string',
      Type: 'string',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'string',
          DiscountPercent: 0,
          CurrencyCode: 'string',
          PreferredPrice: 0,
          PreferredPriceText: 'string',
          IsUndefined: true,
          Quantity: {
            From: 0,
            To: 0,
          },
          ItemsPerUnit: 0,
          PricePerUnit: 0,
          CostPerUnit: 0,
          UnitQuantity: 0,
        },
      ],
      PriceIncludes: 'string',
      UsageLevel: 'string',
      VendorCode: 'string',
      Attributes: [0],
      IsAvailable: true,
    },
  ],
  Currencies: [
    {
      Code: 'USD',
      Name: 'USD',
      Description: 'United States Dollar',
      Symbol: 'USD',
      DecimalSeparator: 'string',
      GroupSeparator: 'string',
    },
  ],
  LowestPrice: {
    IsVisible: true,
    Sequence: 0,
    Price: 0,
    Cost: 0,
    DiscountCode: 'string',
    DiscountPercent: 0,
    CurrencyCode: 'string',
    PreferredPrice: 0,
    PreferredPriceText: 'string',
    IsUndefined: true,
    Quantity: {
      From: 0,
      To: 0,
    },
    ItemsPerUnit: 0,
    PricePerUnit: 0,
    CostPerUnit: 0,
    UnitQuantity: 0,
  },
  HighestPrice: {
    IsVisible: true,
    Sequence: 0,
    Price: 0,
    Cost: 0,
    DiscountCode: 'string',
    DiscountPercent: 0,
    CurrencyCode: 'string',
    PreferredPrice: 0,
    PreferredPriceText: 'string',
    IsUndefined: true,
    Quantity: {
      From: 0,
      To: 0,
    },
    ItemsPerUnit: 0,
    PricePerUnit: 0,
    CostPerUnit: 0,
    UnitQuantity: 0,
  },
  UpdateDate: '2022-01-20T13:19:07.478Z',
  ExpirationDate: '2022-01-20T13:19:07.478Z',
  PublishDate: '2022-01-20T13:19:07.478Z',
  SKU: [
    {
      SKU: 'string',
      Values: [0],
      IsAvailable: true,
    },
  ],

  // Added for Display
  PriceIncludes: 'Price includes: 1 color, 1 or 2 sides or wrap, 2 colors max.',
  Discount: 'Discount tag here',
  Variant: [
    {
      Code: 'DLHF',
      Name: 'Black',
      ImageUrl: 'media/31280153',
      VendorCode: '50',
      SKU: 'B14285502',
      $index: 3,
    },
    {
      Code: 'DROG',
      Name: 'Burnt Orange',
      ImageUrl: 'media/31280156',
      VendorCode: '66',
      SKU: 'B14285662',
    },
    {
      Code: 'MEBL',
      Name: 'Columbia Blue',
      ImageUrl: 'media/31280159',
      VendorCode: '26',
      SKU: 'B14285262',
    },
    {
      Code: 'DRGN',
      Name: 'Forest',
      ImageUrl: 'media/31280162',
      VendorCode: '54',
      SKU: 'B14285542',
    },
    {
      Code: 'DRYE',
      Name: 'Gold',
      ImageUrl: 'media/31280165',
      VendorCode: '12',
      SKU: 'B14285122',
    },
    {
      Code: 'FLGN',
      Name: 'Lime',
      ImageUrl: 'media/31280168',
      VendorCode: '16',
      SKU: 'B14285162',
    },
    {
      Code: 'DRRD',
      Name: 'Maroon',
      ImageUrl: 'media/31280171',
      VendorCode: '53',
      SKU: 'B14285532',
    },
    {
      Code: 'DRBL',
      Name: 'Navy',
      ImageUrl: 'media/31280174',
      VendorCode: '65',
      SKU: 'B14285652',
    },
    {
      Code: 'FGRI',
      Name: 'OD Green',
      ImageUrl: 'media/31280177',
      VendorCode: '19',
      SKU: 'B14285192',
    },
    {
      Code: 'MEPL',
      Name: 'Purple',
      ImageUrl: 'media/31280180',
      VendorCode: '67',
      SKU: 'B14285672',
    },
    {
      Code: 'MERD',
      Name: 'Red',
      ImageUrl: 'media/31280183',
      VendorCode: '70',
      SKU: 'B14285702',
    },
    {
      Code: 'FLBL',
      Name: 'Royal',
      ImageUrl: 'media/31280186',
      VendorCode: '75',
      SKU: 'B14285752',
    },
    {
      Code: 'LIBR',
      Name: 'Sand',
      ImageUrl: 'media/31280189',
      VendorCode: '73',
      SKU: 'B14285732',
    },
    {
      Code: 'ETWF',
      Name: 'White',
      ImageUrl: 'media/31280192',
      VendorCode: '00',
      SKU: 'B14285002',
    },
    {
      Code: 'ETWF',
      Name: 'Neon Pink',
      VendorCode: '00',
      SKU: 'B14285002',
    },
  ],
  Sizes: 'S, M, L, XL, 2XL, 3XL',
  ImprintMethods: 'Embroidery, Screenprint Unimpinted',
  displayedColumnPricing: ['quantity', 'pricePerUnit'],
  dataSourcePricing: [
    { quantity: '50-99', pricePerUnit: '$22.50' },
    { quantity: '100-249', pricePerUnit: '$20.00' },
    { quantity: '250+', pricePerUnit: '$18.50' },
  ],
  displayedColumnAdditionalCharges: ['additionalCharges', 'cost'],
  dataSourceAdditionalCharges: [
    { additionalCharges: 'Setup fee', cost: '$40.00' },
    { additionalCharges: 'Silkscreen Extra Location', cost: '$0.25/ea' },
  ],
  displayedColumnShippingMethod: ['shippingMethod', 'cost'],
  dataSourceShippingMethod: [
    { shippingMethod: 'Standard shipping', cost: '$12.00' },
    { shippingMethod: 'Rush shipping', cost: '$50.00' },
  ],
  // Added for Display
};
